<?php
		define('TWITTER_USER_TIMELINE_USER','QuanticaLabs');
		define('TWITTER_USER_TIMELINE_COUNT','10');
		
		define('TWITTER_USER_TIMELINE_CONSUMER_KEY','');
		define('TWITTER_USER_TIMELINE_CONSUMER_SECRET','');
		define('TWITTER_USER_TIMELINE_ACCESS_TOKEN','');
		define('TWITTER_USER_TIMELINE_ACCESS_TOKEN_SECRET','');
?>